/**** Table structure for `csf_acl` table *****/
DROP TABLE IF EXISTS `csf_acl`;
CREATE TABLE `csf_acl` (                                 
		   `csf_acl_id` bigint(20) NOT NULL auto_increment,       
		   `form_id` bigint(20) default NULL,                     
		   `groupid` bigint(20) default NULL,                     
		   PRIMARY KEY  (`csf_acl_id`)                            
		 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;    

/**** Table structure for `csf_attributes` table *****/
DROP TABLE IF EXISTS `csf_attributes`;
CREATE TABLE `csf_attributes` (                                
                  `attr_id` bigint(20) NOT NULL auto_increment,                
                  `attr_name` varchar(100) default NULL,                       
                  `attr_display_label` varchar(150) default NULL,              
                  `attr_type` enum('s','t','a','d','f','r','c') default NULL,  
                  `attr_max_length` int(11) default NULL,                      
                  `attr_required` enum('y','n') default 'n',                   
                  `attr_validation` varchar(100) default NULL,                 
                  `attr_relational` enum('y','n') default 'n',                 
                  `attr_relational_table` varchar(100) default NULL,           
                  `attr_relational_col` varchar(100) default NULL,             
                  `attr_select_options` text,                                  
                  `attr_index` int(11) NOT NULL default '0',                   
                  `attr_fixed_text` text,                                      
                  `attr_status` enum('y','n') default 'y',                     
                  `attr_html` text,                                            
                  `attr_label_show` enum('y','n') default 'y',                 
                  `attr_validation_script` text,                               
                  `create_date` date default NULL,                             
                  `modify_date` date default NULL,                             
                  PRIMARY KEY  (`attr_id`)                                     
                )  ENGINE=InnoDB DEFAULT CHARSET=utf8;   


/**** Table structure for `csf_form_data` table *****/
DROP TABLE IF EXISTS `csf_form_data`;
CREATE TABLE `csf_form_data` (                           
                 `form_data_id` bigint(20) NOT NULL auto_increment,     
                 `form_id` bigint(20) default NULL,                     
                 `encounter` bigint(20) default NULL,                   
                 `create_date` date default NULL,                       
                 `modified_date` date default NULL,                                              
                 PRIMARY KEY  (`form_data_id`)                          
               ) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

/**** Table structure for `csf_forms` table *****/
DROP TABLE IF EXISTS `csf_forms`;
CREATE TABLE `csf_forms` (                               
             `form_id` bigint(20) NOT NULL auto_increment,          
             `form_name` varchar(100) default NULL,                 
             `form_active` enum('y','n') default NULL,              
             `form_html` text,                                      
             `create_date` date default NULL,                       
             `modified_date` date default NULL,                     
             PRIMARY KEY  (`form_id`)                               
           ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/**** Table structure for `csf_forms_attributes` table *****/
DROP TABLE IF EXISTS `csf_forms_attributes`;
CREATE TABLE `csf_forms_attributes` (                     
                        `form_attr_id` bigint(20) NOT NULL auto_increment,      
                        `form_id` bigint(20) default NULL,                      
                        `attr_id` bigint(20) default NULL,                      
                        `form_attr_label` varchar(255) default NULL,            
                        `form_attr_row_index` int(11) default NULL,             
                        `form_attr_col_index` int(11) default NULL,             
                        `form_attr_active` enum('y','n') default 'y',           
                        `form_attr_checked` int(11) default '0',                
                        `create_date` date default NULL,                        
                        `modified_date` date default NULL,                      
                        PRIMARY KEY  (`form_attr_id`)                           
                      ) ENGINE=InnoDB DEFAULT CHARSET=utf8;  








insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('1','tbFirstName','First Name','t','20','n','character','','','',NULL,'1','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;First Name&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbFirstName&quot; name=&quot;tbFirstName&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;20&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;character&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbFirstName\\&quot;).value.length &gt; 20){ alert(\\&quot;The tbFirstName length should not be more than 20\\&quot;); document.getElementById(\\&quot;tbFirstName\\&quot;).focus(); return false;} regExp = /^[A-Za-z ]*$/; if ((document.getElementById(\\&quot;tbFirstName\\&quot;).value != \\\'\\\') &amp;&amp; !regExp.test(document.getElementById(\\&quot;tbFirstName\\&quot;).value)) { alert(\\&quot;Please enter valid Character value for  tbFirstName\\&quot;);	document.getElementById(\\&quot;tbFirstName\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('2','tbMiddleName','Middle Name','t','1','n','character','','','',NULL,'2','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Middle Name&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbMiddleName&quot; name=&quot;tbMiddleName&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;1&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;character&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbMiddleName\\&quot;).value.length &gt; 1){ alert(\\&quot;The tbMiddleName length should not be more than 1\\&quot;); document.getElementById(\\&quot;tbMiddleName\\&quot;).focus(); return false;} regExp = /^[A-Za-z ]*$/; if ((document.getElementById(\\&quot;tbMiddleName\\&quot;).value != \\\'\\\') &amp;&amp; !regExp.test(document.getElementById(\\&quot;tbMiddleName\\&quot;).value)) { alert(\\&quot;Please enter valid Character value for  tbMiddleName\\&quot;);	document.getElementById(\\&quot;tbMiddleName\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('3','tbLastName','Last Name','t','20','n','character','','','',NULL,'3','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Last Name&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbLastName&quot; name=&quot;tbLastName&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;20&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;character&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbLastName\\&quot;).value.length &gt; 20){ alert(\\&quot;The tbLastName length should not be more than 20\\&quot;); document.getElementById(\\&quot;tbLastName\\&quot;).focus(); return false;} regExp = /^[A-Za-z ]*$/; if ((document.getElementById(\\&quot;tbLastName\\&quot;).value != \\\'\\\') &amp;&amp; !regExp.test(document.getElementById(\\&quot;tbLastName\\&quot;).value)) { alert(\\&quot;Please enter valid Character value for  tbLastName\\&quot;);	document.getElementById(\\&quot;tbLastName\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('4','tbAge','Age','t','15','n','numeric','','','',NULL,'4','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Age&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbAge&quot; name=&quot;tbAge&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;15&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;numeric&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbAge\\&quot;).value.length &gt; 15){ alert(\\&quot;The tbAge length should not be more than 15\\&quot;); document.getElementById(\\&quot;tbAge\\&quot;).focus(); return false;} regExp = /^[0-9 ]*$/; if ((document.getElementById(\\&quot;tbAge\\&quot;).value != \\\'\\\') &amp;&amp; !regExp.test(document.getElementById(\\&quot;tbAge\\&quot;).value)) { alert(\\&quot;Please enter valid Number(Numeric) value for  tbAge\\&quot;);	document.getElementById(\\&quot;tbAge\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('5','dtDate','Date','d',NULL,'n','','','','',NULL,'5','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Date&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input style=\'width:150px;\' readonly type=\'text\' id=&quot;dtDate&quot; name=&quot;dtDate&quot; onkeyup=\'datekeyup(this,mypcc)\' onblur=\'dateblur(this,mypcc)\' title=\'yyyy-mm-dd\'&gt;&lt;img src=\'/interface/pic/show_calendar.gif\' align=\'absbottom\' width=\'24\' height=\'22\' id=\'img_dtDate\' border=\'0\' alt=\'[?]\' style=\'cursor:pointer\' title=\'Click here to choose a date\' &gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Date&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('6','dtDOB','DOB','d',NULL,'n','','','','',NULL,'6','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;DOB&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input style=\'width:150px;\' readonly type=\'text\' id=&quot;dtDOB&quot; name=&quot;dtDOB&quot; onkeyup=\'datekeyup(this,mypcc)\' onblur=\'dateblur(this,mypcc)\' title=\'yyyy-mm-dd\'&gt;&lt;img src=\'/interface/pic/show_calendar.gif\' align=\'absbottom\' width=\'24\' height=\'22\' id=\'img_dtDOB\' border=\'0\' alt=\'[?]\' style=\'cursor:pointer\' title=\'Click here to choose a date\' &gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Date&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('7','rbHPI','HPI','r',NULL,'n','','','','','Yes,No','7','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;HPI&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;rbHPI&quot; name=&quot;rbHPI&quot; type=\'radio\' style=\'width:20px;\' value=&quot;Yes&quot;&gt;Yes&lt;input id=&quot;rbHPI&quot; name=&quot;rbHPI&quot; type=\'radio\' style=\'width:20px;\' value=&quot;No&quot;&gt;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Radio Button&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('8','taSymptoms','Symptoms','a','60','n','','','','',NULL,'8','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Symptoms&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;textarea id=&quot;taSymptoms&quot; name=&quot;taSymptoms&quot; row=\'3\' col=\'4\'&gt;&lt;/textarea&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Area&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;60&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;taSymptoms\\&quot;).value.length &gt; 60){ alert(\\&quot;The taSymptoms length should not be more than 60\\&quot;); document.getElementById(\\&quot;taSymptoms\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('9','tbLMP','LMP','t','30','n','','','','',NULL,'9','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;LMP&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbLMP&quot; name=&quot;tbLMP&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;30&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbLMP\\&quot;).value.length &gt; 30){ alert(\\&quot;The tbLMP length should not be more than 30\\&quot;); document.getElementById(\\&quot;tbLMP\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('10','tbBP','BP','t','10','n','','','','',NULL,'10','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;BP&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbBP&quot; name=&quot;tbBP&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;10&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbBP\\&quot;).value.length &gt; 10){ alert(\\&quot;The tbBP length should not be more than 10\\&quot;); document.getElementById(\\&quot;tbBP\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('11','tbWeight','Weight','t','10','n','','','','',NULL,'11','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Weight&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbWeight&quot; name=&quot;tbWeight&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;10&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbWeight\\&quot;).value.length &gt; 10){ alert(\\&quot;The tbWeight length should not be more than 10\\&quot;); document.getElementById(\\&quot;tbWeight\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('12','tbHeight','Height','t','10','n','','','','',NULL,'12','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Height&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbHeight&quot; name=&quot;tbHeight&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;10&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbHeight\\&quot;).value.length &gt; 10){ alert(\\&quot;The tbHeight length should not be more than 10\\&quot;); document.getElementById(\\&quot;tbHeight\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('13','tbBloodLosscc','Blood Loss cc','t','15','n','','','','',NULL,'13','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Blood Loss cc&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;input id=&quot;tbBloodLosscc&quot; name=&quot;tbBloodLosscc&quot; type=\'text\'&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Text Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;15&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','if(document.getElementById(\\&quot;tbBloodLosscc\\&quot;).value.length &gt; 15){ alert(\\&quot;The tbBloodLosscc length should not be more than 15\\&quot;); document.getElementById(\\&quot;tbBloodLosscc\\&quot;).focus(); return false;}',now(),now());
insert into `csf_attributes` (`attr_id`, `attr_name`, `attr_display_label`, `attr_type`, `attr_max_length`, `attr_required`, `attr_validation`, `attr_relational`, `attr_relational_table`, `attr_relational_col`, `attr_select_options`, `attr_index`, `attr_fixed_text`, `attr_status`, `attr_html`, `attr_label_show`, `attr_validation_script`, `create_date`, `modify_date`) values('14','sbGender','Gender','s',NULL,'n','','n','','','Male,Female','14','','y','&lt;table style=\'font-family:arial;font-size:14px;width:90%\' cellspacing=\'2\'&gt;&lt;tr style=\'bgcolor:#fff;\'&gt;&lt;td style=\'width:25%;border-width:0px;\'&gt;Gender&lt;/td&gt;&lt;/td&gt;&lt;td style=\'width:75%;border-width:0px;\'&gt;&lt;select id=&quot;sbGender&quot; name=&quot;sbGender&quot;&gt;&lt;option value=\'Male\'&gt;Male&lt;/option&gt;&lt;option value=\'Female\'&gt;Female&lt;/option&gt;&lt;/select&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:14px;\'&gt;&lt;td colspan=\'2\' style=\'border-width:0px;\'&gt;&lt;div id=\'tableDiv\' style=\'display:none;\'&gt;&lt;table border=\'1\' width=\'300px\' cellpadding=\'4\'&gt;&lt;tr style=\'border:1px solid;font-size:15px;color:#bc1212;background-color:#FFF;\'&gt;&lt;td colspan=\'2\' align=\'center\'&gt;Attribute Properties&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'background-color:#CEE4FF;\'&gt;&lt;td width=\'140px\' style=\'text-align:center;\'&gt;&lt;b&gt;Name&lt;/b&gt;&lt;/td&gt;&lt;td style=\'text-align:center;\'&gt;&lt;b&gt;Value&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td &gt;Type&lt;/td&gt;&lt;td&gt;&amp;nbsp;Select Box&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td &gt;Required&lt;/td&gt;&lt;td&gt;&amp;nbsp;No&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#E3EFFF;\'&gt;&lt;td&gt;Max Length&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;tr style=\'font-size:12px;background-color:#FFF;\'&gt;&lt;td&gt;Input validation&lt;/td&gt;&lt;td&gt;&amp;nbsp;n/a&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;','y','',now(),now());

ALTER TABLE csf_form_data ADD COLUMN `attribute_1` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_2` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_3` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_4` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_5` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_6` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_7` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_8` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_9` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_10` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_11` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_12` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_13` text;
ALTER TABLE csf_form_data ADD COLUMN `attribute_14` text;




